"""
Django settings for NashCRM project.

Generated by 'django-admin startproject' using Django 5.2.3.

🚀 ОПТИМІЗОВАНО для максимальної продуктивності CRM системи
Включає кешування, індекси, моніторинг та безпеку
"""
import os
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q^cstj+vp83u^gqy_864z5um7sviic5=bfnl%esn6p4-jzk^3='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'nashcrm.onrender.com',
    'localhost',
    '127.0.0.1',
]

# 🚀 ОПТИМІЗОВАНІ НАЛАШТУВАННЯ REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 🚀 ДОДАНО: Пагінація для великих списків
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Обмежуємо кількість записів на сторінку

    # 🚀 ДОДАНО: Оптимізовані рендерери
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

    # 🚀 ДОДАНО: Throttling для захисту від перевантаження
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'reports': '60/hour',  # Обмежуємо звіти
    }
}

# Application definition
GOOGLE_MAPS_API_KEY = "AIzaSyCbJKRdLawZO1Y61MORHULsFbxGbQLlrsk"

ASGI_APPLICATION = "NashCRM.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# 🚀 ОПТИМІЗОВАНІ JWT НАЛАШТУВАННЯ
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),

    # 🚀 ДОДАНО: Додаткові налаштування безпеки
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "UPDATE_LAST_LOGIN": True,
}

INSTALLED_APPS = [
    'corsheaders',
    'channels',
    'unfold',
    'whatsapp',
    'rest_framework',
    'backend',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 🚀 ОПТИМІЗОВАНИЙ MIDDLEWARE З КЕШУВАННЯМ ТА МОНІТОРИНГОМ
MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',  # 🚀 КЕШУВАННЯ - на початок
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'backend.middleware.PerformanceMiddleware',       # 🚀 МОНІТОРИНГ ПРОДУКТИВНОСТІ
    'django.middleware.cache.FetchFromCacheMiddleware',  # 🚀 КЕШУВАННЯ - в кінець
]

ROOT_URLCONF = 'NashCRM.urls'

# 🚀 ОПТИМІЗОВАНІ ШАБЛОНИ З КЕШУВАННЯМ
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 🚀 ДОДАНО: Кешування шаблонів для продуктивності
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ] if not DEBUG else [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'NashCRM.wsgi.application'

# 🚀 ОПТИМІЗОВАНА БАЗА ДАНИХ
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 🚀 ДОДАНО: Оптимізація SQLite
        'OPTIONS': {
            'timeout': 20,
            'init_command': """
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;
                PRAGMA cache_size=1000;
                PRAGMA temp_store=memory;
                PRAGMA foreign_keys=ON;
            """,
        },
    }
}

# 🚀 КРИТИЧНО ВАЖЛИВО: НАЛАШТУВАННЯ КЕШУВАННЯ
CACHES = {
    'default': {
        # Спробуйте Redis спочатку (найкраща продуктивність)
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'KEY_PREFIX': 'nashcrm_cache',
        'TIMEOUT': 300,  # 5 хвилин за замовчуванням
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        }
    } if os.environ.get('REDIS_URL') or os.path.exists('/usr/bin/redis-server') else {
        # Fallback до database cache якщо Redis недоступний
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# 🚀 НАЛАШТУВАННЯ СЕСІЙ З КЕШУВАННЯМ
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 години

# 🚀 НАЛАШТУВАННЯ КЕШУВАННЯ СТОРІНОК
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 хвилин
CACHE_MIDDLEWARE_KEY_PREFIX = 'nashcrm'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'uk'
TIME_ZONE = 'Europe/Kyiv'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# 🚀 ОПТИМІЗОВАНІ СТАТИЧНІ ФАЙЛИ
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 🚀 ДОДАНО: Оптимізація статичних файлів для продакшену
if not DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🚀 НАЛАШТУВАННЯ ЛОГУВАННЯ ДЛЯ МОНІТОРИНГУ ПРОДУКТИВНОСТІ
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'performance': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'slow_queries.log',
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'performance',
        },
        'performance_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'performance.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 3,
            'formatter': 'performance',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'handlers': ['file'],
            'propagate': False,
        },
        'nashcrm.performance': {
            'level': 'INFO',
            'handlers': ['console', 'performance_file'],
            'propagate': False,
        },
        'django.request': {
            'level': 'ERROR',
            'handlers': ['file'],
            'propagate': False,
        },
    },
}

# 🚀 СТВОРЕННЯ ПАПКИ ДЛЯ ЛОГІВ
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# 🚀 НАЛАШТУВАННЯ БЕЗПЕКИ
if not DEBUG:
    # Налаштування для продакшену
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 рік
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Якщо використовуєте HTTPS
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True

# UNFOLD Admin налаштування (без змін, але оптимізовано)
def dashboard_callback(request, context):
    context.update({"sample": "example"})
    return context

def environment_callback(request):
    return

def badge_callback(request):
    return 3

def permission_callback(request):
    return request.user.has_perm("sample_app.change_model")

UNFOLD = {
    "SITE_TITLE": "NashCRM - Система управління лідами",
    "SITE_HEADER": "NashCRM",
    "SITE_SUBHEADER": "Система управління продажами",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("backend/img/crm.png"),
        "dark": lambda request: static("backend/img/crm.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("backend/img/crm.png"),
        "dark": lambda request: static("backend/img/crm.png"),
    },
    "SITE_SYMBOL": "speed",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.svg"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "ENVIRONMENT": environment_callback,
    "ENVIRONMENT_TITLE_PREFIX": environment_callback,
    "DASHBOARD_CALLBACK": dashboard_callback,
    "THEME": "dark",
    "LOGIN": {
        "image": lambda request: static("sample/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:backend_lead_changelist"),
    },
    "STYLES": [
        lambda request: static("backend/css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "base": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
        "primary": {
            "50": "250, 245, 255",
            "100": "243, 232, 255",
            "200": "233, 213, 255",
            "300": "216, 180, 254",
            "400": "192, 132, 252",
            "500": "168, 85, 247",
            "600": "147, 51, 234",
            "700": "126, 34, 206",
            "800": "107, 33, 168",
            "900": "88, 28, 135",
            "950": "59, 7, 100",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("📊 Аналітика та звіти"),
                "separator": True,
                "items": [
                    {
                        "title": "🚀 Dashboard продуктивності",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "📈 Звіт по лідах",
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin_leads_report"),
                    },
                ],
            },
            {
                "title": _("💰 Продажі та фінанси"),
                "separator": True,
                "items": [
                    {
                        "title": "🎯 Ліди",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:backend_lead_changelist"),
                    },
                    {
                        "title": "💸 Фінансові операції",
                        "icon": "payments",
                        "link": reverse_lazy("admin:backend_leadpaymentoperation_changelist"),
                    },
                    {
                        "title": "👥 Клієнти",
                        "icon": "person",
                        "link": reverse_lazy("admin:backend_client_changelist"),
                    },
                ],
            },
            {
                "title": _("⚙️ Налаштування"),
                "separator": True,
                "items": [
                    {
                        "title": "📧 Email інтеграція",
                        "icon": "email",
                        "link": reverse_lazy("admin:backend_emailintegrationsettings_changelist"),
                    },
                    {
                        "title": "👨‍💼 Менеджери",
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:backend_customuser_changelist"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "backend.lead",
            ],
            "items": [
                {
                    "title": _("Всі ліди"),
                    "link": reverse_lazy("admin:backend_lead_changelist"),
                },
                {
                    "title": _("Фінансові операції"),
                    "link": reverse_lazy("admin:backend_leadpaymentoperation_changelist"),
                },
            ],
        },
    ],
}

# 🚀 CORS НАЛАШТУВАННЯ З БЕЗПЕКОЮ
CORS_ALLOWED_ORIGINS = [
    "https://nash-web-crm.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",  # Додатковий порт для розробки
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',  # 🚀 ДОДАНО для кешування
    'x-cache-control',
]

CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 🚀 НАЛАШТУВАННЯ БЕЗПЕКИ
CSRF_TRUSTED_ORIGINS = [
    "https://nash-web-crm.vercel.app",
    "https://nashcrm.onrender.com",
]

# 🚀 ДОДАТКОВІ НАЛАШТУВАННЯ ДЛЯ ПРОДУКТИВНОСТІ

# Оптимізація файлового завантаження
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Налаштування email (якщо використовуєте)
if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    # EMAIL_HOST = 'your-smtp-server.com'
    # EMAIL_HOST_USER = 'your-email@domain.com'
    # EMAIL_HOST_PASSWORD = 'your-password'

# 🚀 КАСТОМНІ НАЛАШТУВАННЯ ДЛЯ CRM
CRM_SETTINGS = {
    # Налаштування кешування для різних типів даних
    'CACHE_TIMEOUTS': {
        'leads_report': 600,  # 10 хвилин
        'funnel_data': 300,   # 5 хвилин
        'client_stats': 300,  # 5 хвилин
        'manager_stats': 900, # 15 хвилин
        'geocoding': 86400,   # 24 години
    },

    # Налаштування пагінації для різних списків
    'PAGINATION': {
        'leads': 50,
        'clients': 30,
        'payments': 100,
        'reports': 20,
    },

    # Налаштування моніторингу продуктивності
    'PERFORMANCE': {
        'SLOW_QUERY_THRESHOLD': 1.0,  # секунди
        'MANY_QUERIES_THRESHOLD': 10,  # кількість запитів
        'LOG_ALL_REQUESTS': DEBUG,
    },

    # Налаштування бізнес-логіки
    'BUSINESS': {
        'DEFAULT_LEAD_STATUS': 'new',
        'MAX_PAYMENT_AMOUNT': 1000000,  # 1 мільйон
        'CURRENCY': 'UAH',
        'AUTO_ASSIGN_LEADS': True,
    }
}

# 🚀 НАЛАШТУВАННЯ ДЛЯ РІЗНИХ СЕРЕДОВИЩ
if os.environ.get('ENVIRONMENT') == 'production':
    DEBUG = False

    # Додаткові налаштування для продакшену
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_TZ = True

    # Оптимізація бази даних для продакшену
    if 'postgresql' in DATABASES['default']['ENGINE']:
        DATABASES['default']['OPTIONS'] = {
            'options': '-c default_transaction_isolation=read_committed'
        }
        DATABASES['default']['CONN_MAX_AGE'] = 600

# 🚀 АВТОМАТИЧНЕ СТВОРЕННЯ ТАБЛИЦІ КЕШУВАННЯ (якщо використовується database cache)
if CACHES['default']['BACKEND'] == 'django.core.cache.backends.db.DatabaseCache':
    import django
    from django.core.management import execute_from_command_line

    try:
        execute_from_command_line(['manage.py', 'createcachetable', '--dry-run'])
    except:
        pass  # Таблиця вже існує або буде створена пізніше

print("🚀 NashCRM налаштування завантажено успішно!")
if DEBUG:
    print("⚡ Режим розробки: моніторинг продуктивності увімкнено")
else:
    print("🔒 Режим продакшену: безпека та оптимізація увімкнено")