# Generated by Django 5.2.3 on 2025-06-24 09:32

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True, verbose_name='Назва акаунта')),
                ('email', models.EmailField(max_length=254, verbose_name='Email логіну')),
                ('app_password', models.CharField(max_length=100, verbose_name='App Password')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=100, verbose_name='IMAP хост')),
                ('folder', models.CharField(default='INBOX', max_length=50, verbose_name='Папка')),
                ('allowed_sender', models.CharField(max_length=255, verbose_name='Дозволений відправник')),
                ('allowed_subject_keyword', models.CharField(blank=True, max_length=100, verbose_name='Ключове слово в темі')),
                ('check_interval', models.PositiveIntegerField(default=30, verbose_name='Інтервал перевірки (сек)')),
            ],
            options={
                'verbose_name': 'Налаштування Email',
                'verbose_name_plural': 'Налаштування Email',
                'indexes': [models.Index(fields=['name'], name='backend_ema_name_f75bf3_idx'), models.Index(fields=['email'], name='backend_ema_email_782e70_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Джерело')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аванс')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вартість доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер замовлення')),
                ('delivery_number', models.CharField(blank=True, max_length=100, verbose_name='ТТН')),
                ('status', models.CharField(choices=[('queued', 'У черзі'), ('in_work', 'Обробляється менеджером'), ('awaiting_prepayment', 'Очікую аванс'), ('preparation', 'В роботу'), ('warehouse_processing', 'Склад'), ('on_the_way', 'В дорозі'), ('completed', 'Завершено'), ('declined', 'Відмовлено')], default='queued', max_length=30, verbose_name='Статус')),
                ('queued_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиція в черзі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адреса (Google)')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Призначено')),
            ],
            options={
                'verbose_name': 'Лід',
                'verbose_name_plural': 'Ліди',
            },
        ),
        migrations.CreateModel(
            name='LeadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.models.lead_file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='backend.lead')),
            ],
            options={
                'verbose_name': 'Файл ліда',
                'verbose_name_plural': 'Файли лідів',
            },
        ),
        migrations.CreateModel(
            name='LeadPaymentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('expected', 'Очікувана сума'), ('received', 'Отримано від водія')], max_length=20, verbose_name='Тип операції')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_operations', to='backend.lead', verbose_name='Лід')),
            ],
            options={
                'verbose_name': 'Фінансова операція по ліду',
                'verbose_name_plural': 'Фінансові операції по лідах',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Назва компанії')),
                ('type', models.CharField(choices=[('individual', 'Фізична особа'), ('company', 'Компанія'), ('vip', 'VIP-клієнт')], default='individual', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('blacklist', 'У чорному списку')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('difficulty_rating', models.PositiveSmallIntegerField(choices=[(1, '1 зірок'), (2, '2 зірок'), (3, '3 зірок'), (4, '4 зірок'), (5, '5 зірок')], default=1, verbose_name='Рейтинг складності')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'indexes': [models.Index(fields=['phone'], name='backend_cli_phone_e64524_idx'), models.Index(fields=['status'], name='backend_cli_status_1ee487_idx'), models.Index(fields=['assigned_to'], name='backend_cli_assigne_4edad3_idx'), models.Index(fields=['created_at'], name='backend_cli_created_e10283_idx'), models.Index(fields=['type', 'status'], name='backend_cli_type_610275_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_type', models.CharField(choices=[('admin', 'Адміністратор'), ('accountant', 'Менеджер')], max_length=20, verbose_name='Тип інтерфейсу')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Користувач інтерфейсу',
                'verbose_name_plural': 'Користувачі інтерфейсу',
                'indexes': [models.Index(fields=['interface_type'], name='backend_cus_interfa_ab8f9a_idx'), models.Index(fields=['user', 'interface_type'], name='backend_cus_user_id_b6a4af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='backend_lea_status_e28d47_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='backend_lea_created_d816c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status_updated_at'], name='backend_lea_status__fd616f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='backend_lea_phone_d5ae0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='backend_lea_assigne_99c651_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='backend_lea_assigne_01d39b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='backend_lea_status_623206_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'status'], name='backend_lea_phone_f3dc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'assigned_to'], name='backend_lea_created_0782bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'price'], name='backend_lea_status_37674a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['operation_type'], name='backend_lea_operati_e342d3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead'], name='backend_lea_lead_id_095223_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['created_at'], name='backend_lea_created_fe1289_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead', 'operation_type'], name='backend_lea_lead_id_b4241a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['operation_type', 'amount'], name='backend_lea_operati_d069c1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['created_at', 'operation_type'], name='backend_lea_created_43615b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead', 'created_at'], name='backend_lea_lead_id_241d87_idx'),
        ),
    ]
