# Generated by Django 5.2.3 on 2025-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Користувач інтерфейсу', 'verbose_name_plural': 'Користувачі інтерфейсу'},
        ),
    ]
