# Generated by Django 5.2.3 on 2025-06-24 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Дзвінок'), ('email', 'Email'), ('meeting', 'Зустріч'), ('sms', 'SMS'), ('messenger', 'Месенджер'), ('social', 'Соціальні мережі'), ('other', 'Інше')], max_length=20, verbose_name='Тип взаємодії')),
                ('direction', models.CharField(choices=[('incoming', 'Вхідний'), ('outgoing', 'Вихідний')], max_length=10, verbose_name='Напрямок')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('outcome', models.CharField(choices=[('positive', 'Позитивний'), ('neutral', 'Нейтральний'), ('negative', 'Негативний'), ('follow_up', 'Потрібен наступний контакт')], max_length=100, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата наступного контакту')),
            ],
            options={
                'verbose_name': 'Взаємодія з клієнтом',
                'verbose_name_plural': 'Взаємодії з клієнтами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва задачі')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('urgent', 'Терміново')], default='medium', max_length=10, verbose_name='Пріоритет')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'Виконується'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=15, verbose_name='Статус')),
                ('due_date', models.DateTimeField(verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Задача по клієнту',
                'verbose_name_plural': 'Задачі по клієнтах',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='akb_segment',
            field=models.CharField(choices=[('vip', 'VIP (>50к грн)'), ('premium', 'Преміум (20-50к грн)'), ('standard', 'Стандарт (5-20к грн)'), ('basic', 'Базовий (<5к грн)'), ('new', 'Новий клієнт'), ('inactive', 'Неактивний')], default='new', max_length=20, verbose_name='Сегмент АКБ'),
        ),
        migrations.AddField(
            model_name='client',
            name='avg_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Середній чек'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перша покупка'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останній контакт'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання покупка'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Джерело першого ліда'),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('messenger', 'Месенджер'), ('sms', 'SMS')], default='phone', max_length=50, verbose_name="Спосіб зв'язку"),
        ),
        migrations.AddField(
            model_name='client',
            name='rfm_frequency',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='F - Frequency (покупок)'),
        ),
        migrations.AddField(
            model_name='client',
            name='rfm_monetary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='M - Monetary (сума)'),
        ),
        migrations.AddField(
            model_name='client',
            name='rfm_recency',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='R - Recency (дні)'),
        ),
        migrations.AddField(
            model_name='client',
            name='rfm_score',
            field=models.CharField(blank=True, max_length=10, verbose_name='RFM Score (111-555)'),
        ),
        migrations.AddField(
            model_name='client',
            name='temperature',
            field=models.CharField(choices=[('cold', 'Холодний лід'), ('warm', 'Теплий лід'), ('hot', 'Гарячий лід'), ('customer', 'Клієнт АКБ'), ('loyal', 'Лояльний клієнт'), ('sleeping', 'Сплячий клієнт')], default='cold', max_length=20, verbose_name='Температура ліда'),
        ),
        migrations.AddField(
            model_name='client',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість замовлень'),
        ),
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Загальна сума покупок'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['temperature'], name='backend_cli_tempera_5b80b4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['akb_segment'], name='backend_cli_akb_seg_22ab78_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['total_spent'], name='backend_cli_total_s_e309b2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_purchase_date'], name='backend_cli_last_pu_ed9a90_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['temperature', 'akb_segment'], name='backend_cli_tempera_199f84_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to', 'temperature'], name='backend_cli_assigne_615e94_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['akb_segment', 'total_spent'], name='backend_cli_akb_seg_93e21a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['rfm_score'], name='backend_cli_rfm_sco_0fbc97_idx'),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='backend.client', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Призначено'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backend.client', verbose_name='Клієнт'),
        ),
    ]
