# Generated by Django 5.2.3 on 2025-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_clientinteraction_clienttask_client_akb_segment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('queued', 'У черзі'), ('in_work', 'Обробляється менеджером'), ('awaiting_prepayment', 'Очікую аванс'), ('preparation', 'В роботу'), ('warehouse_processing', 'Обробка на складі'), ('warehouse_ready', 'Склад - готовий до відгрузки'), ('on_the_way', 'В дорозі'), ('completed', 'Завершено'), ('declined', 'Відмовлено')], default='queued', max_length=30, verbose_name='Статус'),
        ),
    ]
