# Generated by Django 5.2.3 on 2025-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interface_type',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('accountant', 'Бухгалтер'), ('manager', 'Менеджер'), ('warehouse', 'Складський')], max_length=20, verbose_name='Тип інтерфейсу'),
        ),
    ]
