# Generated by Django 5.2.3 on 2025-06-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.lead')),
            ],
            options={
                'verbose_name': 'Платіж по ліду',
                'verbose_name_plural': 'Платежі по лідах',
            },
        ),
    ]
