# Generated by Django 5.2.3 on 2025-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_lead_updated_at_lead_price_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('queued', 'У черзі'), ('in_work', 'У роботі'), ('waiting_payment', 'Очікує оплату'), ('paid', 'Оплачено'), ('declined', 'Відмовлено')], default='new', max_length=20),
        ),
    ]
