# Generated by Django 5.2.3 on 2025-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 зірок'), (2, '2 зірок'), (3, '3 зірок'), (4, '4 зірок'), (5, '5 зірок')], default=1, verbose_name='Рейтинг складності'),
        ),
        migrations.AddField(
            model_name='lead',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='queued_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('queued', 'У черзі'), ('in_work', 'Обробляється менеджером'), ('awaiting_packaging', 'Очікую відповідь від складу'), ('on_the_way', 'В дорозі'), ('awaiting_cash', 'Очікую кошти від водія'), ('paid', 'Оплачено'), ('declined', 'Відмовлено'), ('completed', 'Завершено')], default='new', max_length=30),
        ),
    ]
