# Generated by Django 5.2.3 on 2025-06-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_client_difficulty_rating_lead_actual_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPaymentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('expected', 'Очікувана сума'), ('received', 'Отримано від водія')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_operations', to='backend.lead')),
            ],
            options={
                'verbose_name': 'Фінансова операція по ліду',
                'verbose_name_plural': 'Фінансові операції по лідах',
            },
        ),
    ]
