# Generated by Django 5.2.3 on 2025-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_leadpaymentoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='actual_cash',
        ),
    ]
