# Generated by Django 5.2.3 on 2025-06-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_emailintegrationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
