# Generated by Django 5.2.3 on 2025-06-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Нотатки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('blacklist', 'У чорному списку')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('individual', 'Фізична особа'), ('company', 'Компанія'), ('vip', 'VIP-клієнт')], default='individual', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interface_type',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('accountant', 'Менеджер')], max_length=20, verbose_name='Тип інтерфейсу'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='emailintegrationsettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email логіну'),
        ),
        migrations.AlterField(
            model_name='emailintegrationsettings',
            name='folder',
            field=models.CharField(default='INBOX', max_length=50, verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='emailintegrationsettings',
            name='imap_host',
            field=models.CharField(default='imap.gmail.com', max_length=100, verbose_name='IMAP хост'),
        ),
        migrations.AlterField(
            model_name='emailintegrationsettings',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True, verbose_name='Назва акаунта'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Призначено'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТТН'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='queued_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиція в черзі'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('queued', 'У черзі'), ('in_work', 'Обробляється менеджером'), ('awaiting_packaging', 'Очікую відповідь від складу'), ('on_the_way', 'В дорозі'), ('awaiting_cash', 'Очікую кошти від водія'), ('paid', 'Оплачено'), ('declined', 'Відмовлено'), ('completed', 'Завершено')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='leadpaymentoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='leadpaymentoperation',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='leadpaymentoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='leadpaymentoperation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_operations', to='backend.lead', verbose_name='Лід'),
        ),
        migrations.AlterField(
            model_name='leadpaymentoperation',
            name='operation_type',
            field=models.CharField(choices=[('expected', 'Очікувана сума'), ('received', 'Отримано від водія')], max_length=20, verbose_name='Тип операції'),
        ),
    ]
