# Generated by Django 5.2.3 on 2025-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_client_assigned_to_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailintegrationsettings',
            name='check_interval',
            field=models.PositiveIntegerField(default=30, verbose_name='Інтервал перевірки (сек)'),
        ),
    ]
