# Generated by Django 5.2.3 on 2025-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_emailintegrationsettings_check_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
