# Generated by Django 5.2.3 on 2025-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_lead_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
