# Generated by Django 5.2.3 on 2025-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_lead_actual_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='lead',
            name='full_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Повна адреса (з Google)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область / Регіон'),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
    ]
