# Generated by Django 5.2.3 on 2025-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_lead_city_lead_country_lead_full_address_lead_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='region',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='street',
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адреса (Google)'),
        ),
    ]
