# Generated by Django 5.2.3 on 2025-06-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_lead_city_lead_country_lead_postal_code_lead_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailintegrationsettings',
            name='allowed_sender',
            field=models.CharField(max_length=255, verbose_name='Дозволений відправник'),
        ),
    ]
