# Generated by Django 5.2.3 on 2025-06-23 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_emailintegrationsettings_allowed_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='backend_cli_phone_e64524_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='backend_cli_status_1ee487_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to'], name='backend_cli_assigne_4edad3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='backend_cli_created_e10283_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type', 'status'], name='backend_cli_type_610275_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['interface_type'], name='backend_cus_interfa_ab8f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user', 'interface_type'], name='backend_cus_user_id_b6a4af_idx'),
        ),
        migrations.AddIndex(
            model_name='emailintegrationsettings',
            index=models.Index(fields=['name'], name='backend_ema_name_f75bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailintegrationsettings',
            index=models.Index(fields=['email'], name='backend_ema_email_782e70_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='backend_lea_status_e28d47_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='backend_lea_created_d816c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status_updated_at'], name='backend_lea_status__fd616f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='backend_lea_phone_d5ae0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='backend_lea_assigne_99c651_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='backend_lea_assigne_01d39b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='backend_lea_status_623206_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'status'], name='backend_lea_phone_f3dc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'assigned_to'], name='backend_lea_created_0782bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'price'], name='backend_lea_status_37674a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['operation_type'], name='backend_lea_operati_e342d3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead'], name='backend_lea_lead_id_095223_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['created_at'], name='backend_lea_created_fe1289_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead', 'operation_type'], name='backend_lea_lead_id_b4241a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['operation_type', 'amount'], name='backend_lea_operati_d069c1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['created_at', 'operation_type'], name='backend_lea_created_43615b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentoperation',
            index=models.Index(fields=['lead', 'created_at'], name='backend_lea_lead_id_241d87_idx'),
        ),
    ]
